// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugrbcpzljaaiinynewtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncmJjcHpsamFhaWlueW5ld3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjMwNTYsImV4cCI6MjA3MDUzOTA1Nn0.RjTcxMvsfCay6a1NfoWxb6B0QvXj4owoz5HonrCALvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});